graphql:
  servlet:
    mapping: /api/graphql
    enabled: true

graphiql:
  enabled: true
  mapping: /graphiql
  endpoint:
    graphql: /api/graphql
  cdn:
    enabled: true
    version: 0.12.0

voyager:
  mapping: /voyager
  endpoint: /api/graphql
  enabled: true
